import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      "user_login": "User Login",
      "demo_login": "Demo Login",
      "username_email": "Username or Email",
      "password": "Password",
      "login_account": "Login Your Account",
      "sign_in_google": " Sign in using Google",
      "dont_have_account": "Don't have an Account?",
      "sign_up": "Sign Up",
      "external_tracking": "External Tracking",
      "all_rights_reserved": "All rights reserved. @ 2023 Fleet Stack",
      "dashboard": "Dashboard",
      "status":"Status",
      "map": "Map",
      "list": "List",
      "utility": "Utility",
      "other": "Other",
      "about_us": "About Us",
      "about_aiq": "Fleet Stack offers a Self Hosted Application as per the customer’s requirements and application which can be Installed on the your server.\n\nThe Solution offered by Fleet Stack can be Easily Installed on the Clients Server with their own Logo and Branding and also available in the Local Language to provide them with the complete flexibility of usage of the solution. \n\nFleet Stack also provides with the team of experts for the installation and the other technical aspects regarding to our solution.",
      "add_point": "Add point",
      "change_password": "Change Password",
      "current_password": "Current Password",
      "new_password": "New Password",
      "confirm_password": "Confirm Password",
      "update_password": "Update Password",
      "running_all": "Running All",
      "km": "KM",
      "ai_smartscale": "AI SmartScale",
      "last_week": "Last week",
      "growth": "Growth",
      "fleet_utilization": "Fleet Utilization",
      "all_vehicles": "All Vehicles",
      "units": "Units",
      "stop_vehicles": "Stop Vehicles",
      "running": "Running",
      "eco_driving": "ECO Driving",
      "good": "Good",
      "driver_behavior": "Driver behavior",
      "excellent": "Excellent",
      "vehicle_health": "Vehicle Health",
      "warning": "Warning",
      "you_are_doing": "You're doing great!",
      "keep_it_up":"Keep it up and stick to your plan!",
      "list_of_geofence": "List of Geofence",
      "km_hr": "KM/HR",
      "map_types": "Map Types",
      "default": "Default",
      "satellite": "Satellite",
      "terrain": "Terrain",
      "map_settings": "Map Settings",
      "stopage": "Stopage",
      "poi": "POI",
      "geofence": "Geofence",
      "stop_resume_vehicle": "Stop/Resume Vehicle",
      "search": "Search",
      "all": "All",
      "stop": "Stop",
      "idle": "Idle",
      "info": "Info",
      "history": "History",
      "sensors": "Sensors",
      "details": "Details",
      "vehicle_status": "Vehicle Status",
      "vehicle_current_status": "Vehicle current Status",
      "ignition": "Ignition",
      "ignition_status": "Ignition Status",
      "today_distance": "Today Distance",
      "till_now_driven_km": "Till now driven km",
      "connected_satellite": "number of connected satellite",
      "speed": "Speed",
      "vehicle_moving_km_per_hour": "vehicle moving km per hour",
      "lat_lon": "Lat/Lon",
      "latitude_and_longitude": "latitude and Longitude",
      "add_new_sensor": "Add New Sensor",
      "vehicle": "Vehicle",
      "type_of_vehicle": "Type of Vehicle",
      "imei": "IMEI",
      "gps_device_imei": "GPS device IMEI",
      "gps_device": "GPS Device",
      "device_type": "device type",
      "driver": "Driver",
      "the_person_driving": "The person driving",
      "trackline": "Trackline",
      "smooth_tracking": "Smooth Tracking",
      "ripple": "Ripple",
      "immobilize_vehicle": "Immobilize Vehicle",
      "parking_mode": "Parking Mode",
      "navigate_to_the_vehicle_location": "Navigate to the Vehicle Location",
      "continue": "Continue >>",
      "label": "Label",
      "cluster": "Cluster",
      "select_time": "Select Time",
      "5_min": "5 min.",
      "30_min": "30 min.",
      "1_hour": "1 hour",
      "6_hours": "6 hours",
      "1_day": "1 day",
      "notifications": "Notifications",
      "basic_notification": "Basic Notification",
      "ignition_on": "Ignition On",
      "ignition_off": "Ignition Off",
      "sos": "SOS",
      "power_cut": "Power Cut",
      "vibration": "Vibration",
      "low_battery": "Low Battery",
      "hard_braking": "Hard Braking",
      "hard_acceleration": "Hard Acceleration",
      "hard_cornering": "hardCornering",
      "tampering": "tampering",
      "power_on": "powerOn",
      "power_off": "powerOff",
      "accident": "accident",
      "power_restored": "powerRestored",
      "shock": "shock",
      "parking_enable": "ParkingEnable",
      "door": "door",
      "advance_notification": "Advance Notification",
      "other_navigation": "Other Navigation",
      "checkout_application_settings_and_other_utility": "checkout application settings and other utility",
      "add_your_favorite_place_on_map": "add your favorite place on map",
      "mark_virtual_boundaries_on_maps_as_geofence": "mark virtual boundaries on maps \n as geofence",
      "settings": "Settings",
      "control_your_app_behavior_notifications_and_language": "control your app behavior , notifications\n and language",
      "feedback": "Feedback",
      "share_your_valuable_feedback_to_continuous_improvement": "share your valuable feedback to continuous \nimprovement",
      "privacy_policy": "Privacy Policy",
      "data_and_privacy_policy_about_application_uses": "data and privacy policy about \napplication uses",
      "tutorials": "Tutorials",
      "to_know_more_about_fleet_management_and_application_uses": "to know more about fleet management\n and application uses",
      "enable_disable_parking": "Enable/Disable Parking",
      "list_of_poi": "List of POI",
      "profile": "Profile",
      "support": "Support",
      "logout": "Logout",
      "slower_1x": "Slower (1x)",
      "slow_2x": "Slow (2x)",
      "normal_3x": "Normal (3x)",
      "fast_4x": "Fast (4x)",
      "faster_5x": "Faster (5x)",
      "stoppage": "stoppage",
      "date": "Date",
      "time": "Time",
      "reports": "Reports",
      "stopage_report": "Stopage report",
      "day_wise_summary": "Day wise summary",
      "trip_report": "Trip Report",
      "sensor_report": "Sensor Report",
      "alert_report": "Alert Report",
      "over_speed_report": "Over Speed Report",
      "set_notifications": "Set Notifications",
      "language": "Language",
      "change_the_application_language_as_per_your_compatibility": "change the application language as per\n your compatibility.",
      "set_the_notification_preference_according_to_the_use_cases": "Set the notification preference\n according to the use cases",
      "protect_user_account": "Protect your user account\n by changing the password",
      "support_and_feedback": "Support & Feedback",
      "topic_title": "Topic Title",
      "enter_feedback": "Enter your Feedback here",
      "send_to_admin": "Send to Admin",
      "tracking_link": "Tracking Link",
      "utility_to_optimize_fleet": "The utility used to optimize fleet",
      "replay": "Replay",
      "checkout_playback_history": "Checkout the playback history of your vehicle",
      "vehicle_driven_history": "Vehicle driven history draw a line on map",
      "parking": "Parking",
      "manage_vehicle_parking": "Help you to manage your vehicle parking mode",
      "remote_stop": "Remote Stop",
      "force_stop_resume_vehicle": "Force stop or resume your vehicle ignition",
      "get_fleet_related_reports": "Get your fleet related reports to analyze data",
      "track_link": "Track Link",
      "create_share_external_tracking": "Create and share External\n tracking link to your partners",
      "live_tracking": "Live Tracking",
      "view_history": "View History",
      "add_location": "Add Location",
      "odometer": "Odometer",
      "driven_today": "Driven Today",
      "login": "Login",
      "kindly_enter_username": "Kindly Enter Username",
      "kindly_enter_password": "Kindly Enter Password",
      "login_success": "Login Success",
      "invalid_username_password": "Invalid Username & Password",
      "demo_account_login_success": "Demo account login successfully",
      "choose_language":"Choose Language",
      "my_location":"My Location",
      "updated_successfully": "Setting Updated Successfully",
      "arrival": "Arrival :",
      "departure": "Departure :",
      "stay_time": "Stay Time :",
      "address": "Address :",
      "show_result": "Show Result",
      "input_validation": "input Validation",
      "kindly_select_vehicle": "Kindly select the vehicle.",
      'you_have_selected_more_then_days':"You have selected more then 3 days",
      'todate_should_be_greater_than_fromdate': "Todate should be always greater than fromdate.",
      "kindly_select_the_date": "Kindly Select the Date",
      "result":"result",
      "no_result":"No Result Found",
      "log_report": "log Report",
      "create_link": "Create Link",
      "deleted": "deleted",
      "deleted_successfully": "Deleted Successfully",
      "validation": "validation",
      "kindly_fill":"Kindly Enter the required details before submit.",
      "success":"Success",
      "request_sent_to_admin":"Request Sent to the Admin",
      "password_changed_successfully":"Password Changed Successfully.",
      "result":"Result",
      "parking_mode_enabled":"Parking mode enabled Successfully",
      "parking_mode_disable":"Parking mode disable Successfully",
      "number_mobile_not_available": "driver mobile number is not available",
      "configure_notify": "Configure Notification",
      "notification_set_success":"Notification set successfully",
      "unable_to_update":"Unable to Update try again later",
      "navigation_setting":"Navigation Setting",
      "set_navigation_as": "set navigation as per your preference",
      "reset_nav":"Reset Navigation"


    },
    'hi_IN': {
      "user_login": "यूजर लॉगिन",
      "demo_login": "डेमो लॉगिन",
      "username_email": "यूजरनेम या ईमेल",
      "password": "पासवर्ड",
      "login_account": "अपने अकाउंट में लॉगिन करें",
      "sign_in_google": "Google का उपयोग करके साइन इन करें",
      "dont_have_account": "कोई अकाउंट नहीं है?",
      "sign_up": "साइन अप करें",
      "external_tracking": "बाहरी ट्रैकिंग",
      "all_rights_reserved": "सर्वाधिकार सुरक्षित. @ 2023 Fleet Stack",
      "dashboard": "डैशबोर्ड",
      "map": "नक्शा",
      "list": "सूची",
      "utility": "उपयोगिता",
      "other": "अन्य",
      "about_us": "हमारे बारे में",
      "about_aiq": "Fleet Stack ग्राहक की आवश्यकताओं और आवेदन के अनुसार स्वहोस्ट एप्लिकेशन प्रदान करता है जो अपने सर्वर पर स्थापित किया जा सकता है।\n\nFleet Stack द्वारा प्रदान की गई समाधान, ग्राहक के सर्वर पर आसानी से स्थापित होता है अपनी स्वयं की लोगो और ब्रांडिंग के साथ और स्थानीय भाषा में भी उपलब्ध है ताकि वे समाधान का पूरी तरह से सुलभ उपयोग कर सकें।\n\nFleet Stack ने हमारी समाधान की स्थापना और अन्य तकनीकी पहलुओं के बारे में भी एक टीम प्रदान की है।",
      "add_point": "स्थान जोड़े",
      "change_password": "पासवर्ड बदलें",
      "current_password": "वर्तमान पासवर्ड",
      "new_password": "नया पासवर्ड",
      "confirm_password": "पासवर्ड की पुष्टि कीजिये",
      "update_password": "पासवर्ड अपडेट करें",
      "running_all": "कुल तय दुरी",
      "km": "किलोमीटर",
      "ai_smartscale": "AI स्मार्टस्केल",
      "last_week": "पिछले हफ्ते",
      "growth": "वृद्धि",
      "fleet_utilization": "वाहन उपयोग",
      "all_vehicles": "सभी वाहन",
      "units": "इकाइयां",
      "stop_vehicles": "रुके हुए वाहन",
      "running": "गतिमान",
      "eco_driving": "ECO ड्राइविंग",
      "good": "अच्छा",
      "driver_behavior": "ड्राइवर व्यवहार",
      "excellent": "बहुत अच्छा",
      "vehicle_health": "वाहन स्वास्थ्य",
      "warning": "चेतावनी",
      "you_are_doing": "आप अच्छे से काम कर रहे हैं!",
      "keep_it_up": "जारी रखें और अपनी योजना को पालन करें!",
      "list_of_geofence": "जिओफेन्स की सूची",
      "km_hr": "किलोमीटर/घंटा",
      "map_types": "नक्शे के प्रकार",
      "default": "सामान्य",
      "satellite": "उपग्रह",
      "terrain": "स्थानीय",
      "map_settings": "नक्शे की सेटिंग्स",
      "stopage": "रुकावट",
      "poi": "POI",
      "geofence": "जिओफेन्स",
      "stop_resume_vehicle": "वाहन रोकें/फिर से शुरू करें",
      "search": "खोजें",
      "all": "सब",
      "stop": "रुकें",
      "idle": "निष्क्रिय",
      "info": "जानकारी",
      "history": "इतिहास",
      "sensors": "सेंसर",
      "details": "विवरण",
      "vehicle_status": "वाहन की स्थिति",
      "vehicle_current_status": "वाहन की वर्तमान स्थिति",
      "ignition": "इंजन",
      "ignition_status": "इंजन स्थिति",
      "today_distance": "आज का दूरी",
      "till_now_driven_km": "अब तक चले गए किलोमीटर",
      "connected_satellite": "जुड़े हुए उपग्रहों की संख्या",
      "speed": "गति",
      "vehicle_moving_km_per_hour": "वाहन गतिमान (किलोमीटर /घंटा )",
      "lat_lon": "अक्षांश/रेखांश",
      "latitude_and_longitude": "अक्षांश और रेखांश",
      "add_new_sensor": "नया सेंसर जोड़ें",
      "vehicle": "वाहन",
      "type_of_vehicle": "वाहन का प्रकार",
      "imei": "IMEI",
      "gps_device_imei": "जीपीएस  डिवाइस IMEI",
      "gps_device": "जीपीएस डिवाइस",
      "device_type": "डिवाइस प्रकार",
      "driver": "चालक",
      "the_person_driving": "चालने वाला व्यक्ति",
      "trackline": "ट्रैकलाइन",
      "smooth_tracking": "सुहानी ट्रैकिंग",
      "ripple": "तरंग",
      "immobilize_vehicle": "वाहन असंचालनीय बनाएँ",
      "parking_mode": "पार्किंग मोड",
      "navigate_to_the_vehicle_location": "वाहन स्थान पर नेविगेट करें",
      "continue": "जारी रखें >>",
      "label": "लेबल",
      "cluster": "समूह",
      "select_time": "समय चुनें",
      "5_min": "5 मिनट",
      "30_min": "30 मिनट",
      "1_hour": "1 घंटा",
      "6_hours": "6 घंटे",
      "1_day": "1 दिन",
      "notifications": "नोटिफिकेशन",
      "basic_notification": "मूल नोटिफिकेशन",
      "ignition_on": "इंजन  ऑन",
      "ignition_off": "इंजन  ऑफ",
      "sos": "SOS",
      "power_cut": "बिजली कटौती",
      "vibration": "वाइब्रेशन",
      "low_battery": "निम्न बैटरी",
      "hard_braking": "हार्ड ब्रेकिंग",
      "hard_acceleration": "हार्ड एक्सेलरेशन",
      "hard_cornering": "हार्ड कॉर्नरिंग",
      "tampering": "विधि विरुद्ध कीमती कार्य करना",
      "power_on": "बिजली चालू",
      "power_off": "बिजली बंद",
      "accident": "दुर्घटना",
      "power_restored": "बिजली बहाल",
      "shock": "छाप",
      "parking_enable": "पार्किंग सक्षम करें",
      "door": "दरवाज़ा",
      "advance_notification": "एडवांस नोटिफिकेशन",
      "other_navigation": "अन्य नेविगेशन",
      "checkout_application_settings_and_other_utility": "अनुप्रयोग सेटिंग और अन्य उपयोगी चीजों की जांच करें",
      "add_your_favorite_place_on_map": "मानचित्र पर अपनी पसंदीदा जगह जोड़ें",
      "mark_virtual_boundaries_on_maps_as_geofence": "मानचित्र पर आभासी सीमाएं जैसे जियोफेंस चिह्नें",
      "settings": "सेटिंग्स",
      "control_your_app_behavior_notifications_and_language": "अपने एप्लिकेशन व्यवहार, सूचनाएं \n और भाषा को नियंत्रित करें",
      "feedback": "प्रतिक्रिया",
      "share_your_valuable_feedback_to_continuous_improvement": "निरंतर सुधार के लिए अपनी महत्वपूर्ण प्रतिक्रिया साझा करें",
      "privacy_policy": "गोपनीयता नीति",
      "data_and_privacy_policy_about_application_uses": "अनुप्रयोग का उपयोग के बारे में डेटा\n और गोपनीयता नीति",
      "tutorials": "ट्यूटोरियल्स",
      "to_know_more_about_fleet_management_and_application_uses": "फ्लीट प्रबंधन और अनुप्रयोग का उपयोग जानने के लिए",
      "enable_disable_parking": "पार्किंग सक्षम/अक्षम करें",
      "list_of_poi": "POI की सूची",
      "profile": "प्रोफाइल",
      "support": "समर्थन",
      "logout": "लोग आउट",
      "slower_1x": "धीमा (1x)",
      "slow_2x": "धीमा (2x)",
      "normal_3x": "सामान्य (3x)",
      "fast_4x": "तेज (4x)",
      "faster_5x": "अधिक तेज (5x)",
      "stoppage": "रुकावट",
      "date": "तारीख",
      "time": "समय",
      "reports": "रिपोर्ट",
      "stopage_report": "रुकावट रिपोर्ट",
      "day_wise_summary": "दिन वार सारांश",
      "trip_report": "यात्रा रिपोर्ट",
      "sensor_report": "सेंसर रिपोर्ट",
      "alert_report": "चेतावनी रिपोर्ट",
      "over_speed_report": "ओवर स्पीड रिपोर्ट",
      "set_notifications": "सूचनाएं सेट करें",
      "language": "भाषा",
      "change_the_application_language_as_per_your_compatibility": "अपनी पसंद के अनुसार अनुप्रयोग भाषा बदलें",
      "set_the_notification_preference_according_to_the_use_cases": "उपयोग केस के अनुसार अधिसूचना प्राथमिकता सेट करें",
      "protect_user_account": "पासवर्ड बदलकर अपने यूजर अकाउंट सुरक्षित रखें",
      "support_and_feedback": "समर्थन और प्रतिक्रिया",
      "topic_title": "विषय शीर्षक",
      "enter_feedback": "अपनी प्रतिक्रिया यहां दर्ज करें",
      "send_to_admin": "व्यवस्थापक को भेजें",
      "tracking_link": "ट्रैकिंग लिंक",
      "utility_to_optimize_fleet": "वाहन के उपयोग को संरक्षित करे",
      "replay": "रिप्ले",
      "checkout_playback_history": "अपने वाहन की प्लेबैक इतिहास की जाँच करें",
      "vehicle_driven_history": "वाहन चलाया गया इतिहास मानचित्र पर एक रेखा खींचें",
      "parking": "पार्किंग",
      "manage_vehicle_parking": "अपने वाहन पार्किंग मोड को\n प्रबंधित करने में आपकी मदद करें",
      "remote_stop": "रिमोट स्टॉप",
      "force_stop_resume_vehicle": "वाहन इग्निशन को बंद या फिर से चालू करें",
      "get_fleet_related_reports": "अपने फ्लीट से संबंधित रिपोर्ट्स\n प्राप्त करें जो डेटा विश्लेषित करने के लिए होगे",
      "track_link": "ट्रैक लिंक",
      "create_share_external_tracking": "एक्सटर्नल ट्रैकिंग लिंक बनाएँ \nऔर अपने भागीदारों के साथ साझा करें",
      "live_tracking": "लाइव ट्रैकिंग",
      "view_history": "इतिहास देखें",
      "add_location": "स्थान जोड़ें",
      "odometer": "ओडोमीटर",
      "driven_today": "आज चलाई गई",
      "login": "लॉग इन करें",
      "kindly_enter_username": "कृपया उपयोगकर्ता नाम दर्ज करें",
      "kindly_enter_password": "कृपया पासवर्ड दर्ज करें",
      "login_success": "लॉगिन सफलता",
      "invalid_username_password": "अमान्य उपयोगकर्ता नाम और पासवर्ड",
      "demo_account_login_success": "डेमो खाता सफलतापूर्वक लॉगइन हुआ",
      "choose_language":"भाषा चुनें",
      'no_data':"No data count",
    },

    'es_ES': {
      "user_login": "Inicio de sesión de usuario",
      "demo_login": "Inicio de sesión de demostración",
      "username_email": "Nombre de usuario o correo electrónico",
      "password": "Contraseña",
      "login_account": "Inicie sesión en su cuenta",
      "sign_in_google": " Iniciar sesión con Google",
      "dont_have_account": "¿No tienes una cuenta?",
      "sign_up": "Regístrate",
      "external_tracking": "Seguimiento externo",
      "all_rights_reserved": "Todos los derechos reservados. @ 2023 Fleet Stack",
      "dashboard": "Tablero",
      "map": "Mapa",
      "list": "Lista",
      "utility": "Utilidad",
      "other": "Otro",
      "about_us": "Acerca de nosotros",
      "about_aiq": "Fleet Stack ofrece una aplicación autoservicio según los requisitos y la aplicación del cliente, que se puede instalar en su servidor.\n\nLa solución ofrecida por Fleet Stack se puede instalar fácilmente en el servidor del cliente con su propio logotipo y marca y también está disponible en el idioma local para proporcionarles la completa flexibilidad de uso de la solución. \n\nFleet Stack también proporciona un equipo de expertos para la instalación y otros aspectos técnicos relacionados con nuestra solución.",
      "add_point": "Añadir punto",
      "change_password": "Cambiar contraseña",
      "current_password": "Contraseña actual",
      "new_password": "Nueva contraseña",
      "confirm_password": "Confirmar contraseña",
      "update_password": "Actualizar contraseña",
      "running_all": "Ejecutando todo",
      "km": "KM",
      "ai_smartscale": "Escala inteligente AI",
      "last_week": "La semana pasada",
      "growth": "Crecimiento",
      "fleet_utilization": "Utilización de la flota",
      "all_vehicles": "Todos los vehículos",
      "units": "Unidades",
      "stop_vehicles": "Vehículos detenidos",
      "running": "En ejecución",
      "eco_driving": "Conducción ecológica",
      "good": "Bueno",
      "driver_behavior": "Comportamiento del conductor",
      "excellent": "Excelente",
      "vehicle_health": "Salud del vehículo",
      "warning": "Advertencia",
      "you_are_doing": "¡Lo estás haciendo genial!",
      "keep_it_up":"¡Sigue así y cúmple con tu plan!",
      "list_of_geofence": "Lista de geocerca",
      "km_hr": "KM/HR",
      "map_types": "Tipos de mapa",
      "default": "Por defecto",
      "satellite": "Satélite",
      "terrain": "Terreno",
      "map_settings": "Configuración del mapa",
      "stopage": "Parada",
      "poi": "POI",
      "geofence": "Geocerca",
      "stop_resume_vehicle": "Detener/Reanudar vehículo",
      "search": "Buscar",
      "all": "Todos",
      "stop": "Detener",
      "idle": "Inactivo",
      "info": "Información",
      "history": "Historia",
      "sensors": "Sensores",
      "details": "Detalles",
      "vehicle_status": "Estado del vehículo",
      "vehicle_current_status": "Estado actual del vehículo",
      "ignition": "Encendido",
      "ignition_status": "Estado del encendido",
      "today_distance": "Distancia de hoy",
      "till_now_driven_km": "Hasta ahora km conducidos",
      "connected_satellite": "número de satélites conectados",
      "speed": "Velocidad",
      "vehicle_moving_km_per_hour": "vehículo en movimiento km por hora",
      "lat_lon": "Lat/Lon",
      "latitude_and_longitude": "latitud y longitud",
      "add_new_sensor": "Añadir nuevo sensor",
      "vehicle": "Vehículo",
      "type_of_vehicle": "Tipo de vehículo",
      "imei": "IMEI",
      "gps_device_imei": "IMEI del dispositivo GPS",
      "gps_device": "Dispositivo GPS",
      "device_type": "tipo de dispositivo",
      "driver": "Conductor",
      "the_person_driving": "La persona que conduce",
      "trackline": "Línea de rastreo",
      "smooth_tracking": "Seguimiento suave",
      "ripple": "Ondulación",
      "immobilize_vehicle": "Inmovilizar vehículo",
      "parking_mode": "Modo de aparcamiento",
      "navigate_to_the_vehicle_location": "Navegar a la ubicación del vehículo",
      "continue": "Continuar >>",
      "label": "Etiqueta",
      "cluster": "Agrupación",
      "select_time": "Seleccionar hora",
      "5_min": "5 min.",
      "30_min": "30 min.",
      "1_hour": "1 hora",
      "6_hours": "6 horas",
      "1_day": "1 día",
      "notifications": "Notificaciones",
      "basic_notification": "Notificación básica",
      "ignition_on": "Encendido",
      "ignition_off": "Apagado",
      "sos": "SOS",
      "power_cut": "Corte de energía",
      "vibration": "Vibración",
      "low_battery": "Batería baja",
      "hard_braking": "Frenado brusco",
      "hard_acceleration": "Aceleración brusca",
      "hard_cornering": "Curva brusca",
      "tampering": "Manipulación",
      "power_on": "Encendido",
      "power_off": "Apagado",
      "accident": "Accidente",
      "power_restored": "Energía restaurada",
      "shock": "Choque",
      "parking_enable": "Activar aparcamiento",
      "door": "Puerta",
      "advance_notification": "Notificación avanzada",
      "other_navigation": "Otra navegación",
      "checkout_application_settings_and_other_utility": "Consulte la configuración de la aplicación y otras utilidades",
      "add_your_favorite_place_on_map": "Añade tu lugar favorito en el mapa",
      "mark_virtual_boundaries_on_maps_as_geofence": "Marca los límites virtuales en el mapa como geocerca",
      "settings": "Configuración",
      "control_your_app_behavior_notifications_and_language": "Controla el comportamiento de la aplicación, las notificaciones y el idioma",
      "feedback": "Comentarios",
      "share_your_valuable_feedback_to_continuous_improvement": "Comparte tus valiosos comentarios para una mejora continua",
      "privacy_policy": "Política de privacidad",
      "data_and_privacy_policy_about_application_uses": "Política de datos y privacidad sobre el uso de la aplicación",
      "tutorials": "Tutoriales",
      "to_know_more_about_fleet_management_and_application_uses": "Para obtener más información sobre la gestión de flotas y el uso de la aplicación",
      "enable_disable_parking": "Habilitar/deshabilitar aparcamiento",
      "list_of_poi": "Lista de POI",
      "profile": "Perfil",
      "support": "Soporte",
      "logout": "Cerrar sesión",
      "slower_1x": "Más lento (1x)",
      "slow_2x": "Lento (2x)",
      "normal_3x": "Normal (3x)",
      "fast_4x": "Rápido (4x)",
      "faster_5x": "Más rápido (5x)",
      "stoppage": "Parada",
      "date": "Fecha",
      "time": "Hora",
      "reports": "Informes",
      "stopage_report": "Informe de parada",
      "day_wise_summary": "Resumen por día",
      "trip_report": "Informe de viaje",
      "sensor_report": "Informe de sensor",
      "alert_report": "Informe de alerta",
      "over_speed_report": "Informe de exceso de velocidad",
      "set_notifications": "Configurar notificaciones",
      "language": "Idioma",
      "change_the_application_language_as_per_your_compatibility": "cambie el idioma de la aplicación según su compatibilidad.",
      "set_the_notification_preference_according_to_the_use_cases": "Establezca la preferencia de notificación según los casos de uso",
      "protect_user_account": "Proteja su cuenta de usuario cambiando la contraseña",
      "support_and_feedback": "Soporte y comentarios",
      "topic_title": "Título del tema",
      "enter_feedback": "Ingrese su comentario aquí",
      "send_to_admin": "Enviar al administrador",
      "tracking_link": "Enlace de seguimiento",
      "utility_to_optimize_fleet": "La utilidad utilizada para optimizar la flota",
      "replay": "Reproducir de nuevo",
      "checkout_playback_history": "Consulte el historial de reproducción de su vehículo",
      "vehicle_driven_history": "Historial de conducción del vehículo dibuja una línea en el mapa",
      "parking": "Estacionamiento",
      "manage_vehicle_parking": "Le ayudará a gestionar el modo de estacionamiento de su vehículo",
      "remote_stop": "Detención remota",
      "force_stop_resume_vehicle": "Detenga o reanude el encendido de su vehículo",
      "get_fleet_related_reports": "Obtenga informes relacionados con su flota para analizar los datos",
      "track_link": "Enlace de seguimiento",
      "create_share_external_tracking": "Cree y comparta el enlace de seguimiento externo con sus socios",
      "live_tracking": "Seguimiento en vivo",
      "view_history": "Ver historial",
      "add_location": "Añadir ubicación",
      "odometer": "Odómetro",
      "driven_today": "Conducido hoy",
      "login": "Iniciar sesión",
      "kindly_enter_username": "Ingrese amablemente el nombre de usuario",
      "kindly_enter_password": "Ingrese amablemente la contraseña",
      "login_success": "Inicio de sesión exitoso",
      "invalid_username_password": "Nombre de usuario y contraseña inválidos",
      "demo_account_login_success": "Inicio de sesión en la cuenta de demostración exitoso",
      "choose_language": "Elige idioma",
    },

    'fr_FR': {
      "user_login": "Connexion utilisateur",
      "demo_login": "Connexion démo",
      "username_email": "Nom d'utilisateur ou e-mail",
      "password": "Mot de passe",
      "login_account": "Connectez votre compte",
      "sign_in_google": " Se connecter avec Google",
      "dont_have_account": "Vous n'avez pas de compte?",
      "sign_up": "S'inscrire",
      "external_tracking": "Suivi externe",
      "all_rights_reserved": "Tous droits réservés. © 2023 Fleet Stack",
      "dashboard": "Tableau de bord",
      "map": "Carte",
      "list": "Liste",
      "utility": "Utilité",
      "other": "Autre",
      "about_us": "À propos de nous",
      "about_aiq": "Fleet Stack propose une application hébergée par l'utilisateur en fonction des exigences et de l'application du client, qui peut être installée sur votre serveur.\n\nLa solution proposée par Fleet Stack peut être facilement installée sur le serveur du client avec son propre logo et sa marque, et est également disponible dans la langue locale pour leur offrir une flexibilité complète d'utilisation de la solution.\n\nFleet Stack fournit également une équipe d'experts pour l'installation et les autres aspects techniques concernant notre solution.",
      "add_point": "Ajouter un point",
      "change_password": "Changer le mot de passe",
      "current_password": "Mot de passe actuel",
      "new_password": "Nouveau mot de passe",
      "confirm_password": "Confirmer le mot de passe",
      "update_password": "Mettre à jour le mot de passe",
      "running_all": "En cours de tous",
      "km": "KM",
      "ai_smartscale": "AI SmartScale",
      "last_week": "La semaine dernière",
      "growth": "Croissance",
      "fleet_utilization": "Utilisation de la flotte",
      "all_vehicles": "Tous les véhicules",
      "units": "Unités",
      "stop_vehicles": "Arrêter les véhicules",
      "running": "En cours",
      "eco_driving": "Conduite éco",
      "good": "Bon",
      "driver_behavior": "Comportement du conducteur",
      "excellent": "Excellent",
      "vehicle_health": "Santé du véhicule",
      "warning": "Attention",
      "you_are_doing": "Vous faites du bon travail!",
      "keep_it_up": "Continuez et respectez votre plan!",
      "list_of_geofence": "Liste des zones géographiques",
      "km_hr": "KM/HR",
      "map_types": "Types de cartes",
      "default": "Défaut",
      "satellite": "Satellite",
      "terrain": "Terrain",
      "map_settings": "Paramètres de la carte",
      "stopage": "Arrêt",
      "poi": "POI",
      "geofence": "Zone géographique",
      "stop_resume_vehicle": "Arrêter/Reprendre le véhicule",
      "search": "Rechercher",
      "all": "Tout",
      "stop": "Arrêter",
      "idle": "Inactif",
      "info": "Info",
      "history": "Historique",
      "sensors": "Capteurs",
      "details": "Détails",
      "vehicle_status": "État du véhicule",
      "vehicle_current_status": "État actuel du véhicule",
      "ignition": "Allumage",
      "ignition_status": "État de l'allumage",
      "today_distance": "Distance aujourd'hui",
      "till_now_driven_km": "Km parcourus jusqu'à présent",
      "connected_satellite": "nombre de satellites connectés",
      "speed": "Vitesse",
      "vehicle_moving_km_per_hour": "véhicule parcourant les km par heure",
      "lat_lon": "Lat/Lon",
      "latitude_and_longitude": "latitude et longitude",
      "add_new_sensor": "Ajouter un nouveau capteur",
      "vehicle": "Véhicule",
      "type_of_vehicle": "Type de véhicule",
      "imei": "IMEI",
      "gps_device_imei": "GPS device IMEI",
      "gps_device": "GPS Device",
      "device_type": "type de dispositif",
      "driver": "Chauffeur",
      "the_person_driving": "La personne qui conduit",
      "trackline": "Ligne de piste",
      "smooth_tracking": "Suivi lisse",
      "ripple": "Ondulation",
      "immobilize_vehicle": "Immobiliser le véhicule",
      "parking_mode": "Mode stationnement",
      "navigate_to_the_vehicle_location": "Accéder à l'emplacement du véhicule",
      "continue": "Continuer >>",
      "label": "Étiquette",
      "cluster": "Groupe",
      "select_time": "Sélectionner l'heure",
      "5_min": "5 min.",
      "30_min": "30 min.",
      "1_hour": "1 heure",
      "6_hours": "6 heures",
      "1_day": "1 jour",
      "notifications": "Notifications",
      "basic_notification": "Notification de base",
      "ignition_on": "Allumage On",
      "ignition_off": "Allumage Off",
      "sos": "SOS",
      "power_cut": "Coupe de courant",
      "vibration": "Vibration",
      "low_battery": "Batterie faible",
      "hard_braking": "Freinage violent",
      "hard_acceleration": "Accélération brutale",
      "hard_cornering": "Virage serré",
      "tampering": "Manipulation",
      "power_on": "Allumage",
      "power_off": "Extinction",
      "accident": "Accident",
      "power_restored": "Alimentation restaurée",
      "shock": "Choc",
      "parking_enable": "Parking Enable",
      "door": "Porte",
      "advance_notification": "Notification avancée",
      "other_navigation": "Autre navigation",
      "checkout_application_settings_and_other_utility": "consulter les paramètres de l'application et d'autres utilitaires",
      "add_your_favorite_place_on_map": "ajoutez votre lieu préféré sur la carte",
      "mark_virtual_boundaries_on_maps_as_geofence": "marquer les limites virtuelles sur les cartes en tant que zone géographique",
      "settings": "Paramètres",
      "control_your_app_behavior_notifications_and_language": "contrôlez le comportement de votre application, les notifications et la langue",
      "feedback": "Commentaires",
      "share_your_valuable_feedback_to_continuous_improvement": "partagez vos commentaires précieux pour une amélioration continue",
      "privacy_policy": "Politique de confidentialité",
      "data_and_privacy_policy_about_application_uses": "politique de données et de confidentialité sur l'utilisation de l'application",
      "tutorials": "Tutoriels",
      "to_know_more_about_fleet_management_and_application_uses": "pour en savoir plus sur la gestion de flotte et l'utilisation de l'application",
      "enable_disable_parking": "Activer/Désactiver le stationnement",
      "list_of_poi": "Liste de POI",
      "profile": "Profil",
      "support": "Assistance",
      "logout": "Déconnexion",
      "slower_1x": "Plus lent (1x)",
      "slow_2x": "Lent (2x)",
      "normal_3x": "Normal (3x)",
      "fast_4x": "Rapide (4x)",
      "faster_5x": "Plus rapide (5x)",
      "stoppage": "arrêt",
      "date": "Date",
      "time": "Heure",
      "reports": "Rapports",
      "stopage_report": "Rapport d'arrêt",
      "day_wise_summary": "Résumé journalier",
      "trip_report": "Rapport de voyage",
      "sensor_report": "Rapport de capteur",
      "alert_report": "Rapport d'alerte",
      "over_speed_report": "Rapport de vitesse excessive",
      "set_notifications": "Définir les notifications",
      "language": "Langue",
      "change_the_application_language_as_per_your_compatibility": "modifiez la langue de l'application en fonction de votre compatibilité.",
      "set_the_notification_preference_according_to_the_use_cases": "Définissez les préférences de notification en fonction des cas d'utilisation",
      "protect_user_account": "Protégez votre compte utilisateur en modifiant le mot de passe",
      "support_and_feedback": "Assistance et commentaires",
      "topic_title": "Titre du sujet",
      "enter_feedback": "Entrez vos commentaires ici",
      "send_to_admin": "Envoyer à l'administrateur",
      "tracking_link": "Lien de suivi",
      "utility_to_optimize_fleet": "L'utilité utilisée pour optimiser la flotte",
      "replay": "Rejouer",
      "checkout_playback_history": "Consultez l'historique de lecture de votre véhicule",
      "vehicle_driven_history": "Historique de conduite du véhicule tracé sur la carte",
      "parking": "Stationnement",
      "manage_vehicle_parking": "Aidez-vous à gérer le mode de stationnement de votre véhicule",
      "remote_stop": "Arrêt à distance",
      "force_stop_resume_vehicle": "Arrêtez ou reprenez de force l'allumage de votre véhicule",
      "get_fleet_related_reports": "Obtenez les rapports relatifs à votre flotte pour analyser les données",
      "track_link": "Lien de suivi",
      "create_share_external_tracking": "Créez et partagez un lien de suivi externe avec vos partenaires",
      "live_tracking": "Suivi en direct",
      "view_history": "Voir l'historique",
      "add_location": "Ajouter un emplacement",
      "odometer": "Odomètre",
      "driven_today": "Conduit aujourd'hui",
      "login": "S'identifier",
      "kindly_enter_username": "Veuillez entrer votre nom d'utilisateur",
      "kindly_enter_password": "Veuillez entrer votre mot de passe",
      "login_success": "Connexion réussie",
      "invalid_username_password": "Nom d'utilisateur et mot de passe non valides",
      "demo_account_login_success": "Connexion au compte démo réussie",
      "choose_language":"Choisissez la langue",

    },

    'ar_AE': {
      "user_login": "تسجيل الدخول للمستخدم",
      "demo_login": "تسجيل الدخول التجريبي",
      "username_email": "اسم المستخدم أو البريد الإلكتروني",
      "password": "كلمة المرور",
      "login_account": "تسجيل الدخول إلى حسابك",
      "sign_in_google": "تسجيل الدخول باستخدام Google",
      "dont_have_account": "ليس لديك حساب؟",
      "sign_up": "سجل",
      "external_tracking": "تتبع خارجي",
      "all_rights_reserved": "كل الحقوق محفوظة. © 2023 شركة Fleet Stack",
      "dashboard": "لوحة القيادة",
      "map": "خريطة",
      "list": "قائمة",
      "utility": "خدمة",
      "other": "آخر",
      "about_us": "عنا",
      "about_aiq": "تقدم Fleet Stack تطبيقًا مضيفًا نفسه كما يطلبه العميل والتطبيق يمكن تثبيته على الخادم الخاص بك.\n\nالحل الذي يقدمه Fleet Stack يمكن تثبيته بسهولة على الخادم الخاص بالعملاء مع شعارهم الخاص والعلامة التجارية ويتوفر أيضًا في اللغة المحلية لتمكينهم من الحرية الكاملة في استخدام الحل. \n\nيقدم Fleet Stack أيضًا فريقًا من الخبراء للتثبيت والجوانب التقنية الأخرى المتعلقة بحلنا.",
      "add_point": "إضافة نقطة",
      "change_password": "تغيير كلمة المرور",
      "current_password": "كلمة المرور الحالية",
      "new_password": "كلمة المرور الجديدة",
      "confirm_password": "تأكيد كلمة المرور",
      "update_password": "تحديث كلمة المرور",
      "running_all": "كل التشغيل",
      "km": "كم",
      "ai_smartscale": "AI SmartScale",
      "last_week": "الأسبوع الماضي",
      "growth": "النمو",
      "fleet_utilization": "استخدام الفلات",
      "all_vehicles": "جميع المركبات",
      "units": "وحدات",
      "stop_vehicles": "توقف المركبات",
      "running": "جارٍ",
      "eco_driving": "قيادة ايكو",
      "good": "جيد",
      "driver_behavior": "سلوك السائق",
      "excellent": "ممتاز",
      "vehicle_health": "صحة المركبة",
      "warning": "تحذير",
      "you_are_doing": "أنت تقوم بعمل رائع!",
      "keep_it_up": "استمر في ذلك والالتزام بخطة العمل الخاصة بك!",
      "list_of_geofence": "قائمة المنطقة الجغرافية",
      "km_hr": "كم/ساعة",
      "map_types": "أنواع الخريطة",
      "default": "افتراضي",
      "satellite": "الأقمار الصناعية",
      "terrain": "التربة",
      "map_settings": "إعدادات الخريطة",
      "stopage": "وقفة",
      "poi": "POI",
      "geofence": "المنطقة الجغرافية",
      "stop_resume_vehicle": "توقف/استئناف المركبة",
      "search": "بحث",
      "all": "الكل",
      "stop": "توقف",
      "idle": "غير نشط",
      "info": "معلومات",
      "history": "التاريخ",
      "sensors": "المستشعرات",
      "details": "تفاصيل",
      "vehicle_status": "حالة المركبة",
      "vehicle_current_status": "حالة المركبة الحالية",
      "ignition": "تشغيل",
      "ignition_status": "حالة التشغيل",
      "today_distance": "المسافة اليوم",
      "till_now_driven_km": "حتى الآن قدم km",
      "connected_satellite": "عدد الأقمار الصناعية المتصلة",
      "speed": "السرعة",
      "vehicle_moving_km_per_hour": "المركبة تتحرك كم في الساعة",
      "lat_lon": "خط العرض/خط الطول",
      "latitude_and_longitude": "خط العرض وخط الطول",
      "add_new_sensor": "إضافة مستشعر جديد",
      "vehicle": "مركبة",
      "type_of_vehicle": "نوع المركبة",
      "imei": "IMEI",
      "gps_device_imei": "IMEI جهاز GPS",
      "gps_device": "جهاز GPS",
      "device_type": "نوع الجهاز",
      "driver": "سائق",
      "the_person_driving": "الشخص الذي يقود",
      "trackline": "خط المسار",
      "smooth_tracking": "تتبع ناعم",
      "ripple": "موجة",
      "immobilize_vehicle": "عزل المركبة",
      "parking_mode": "وضع التوقف",
      "navigate_to_the_vehicle_location": "تصفح إلى موقع المركبة",
      "continue": "متابعة >>",
      "label": "علامة",
      "cluster": "علبة",
      "select_time": "اختيار الوقت",
      "5_min": "5 دقائق",
      "30_min": "30 دقيقة",
      "1_hour": "1 ساعة",
      "6_hours": "6 ساعات",
      "1_day": "1 يوم",
      "notifications": "إخطارات",
      "basic_notification": "إخطارات أساسية",
      "ignition_on": "تشغيل",
      "ignition_off": "إيقاف التشغيل",
      "sos": "SOS",
      "power_cut": "قطع الطاقة",
      "vibration": "اهتزاز",
      "low_battery": "بطارية منخفضة",
      "hard_braking": "عجلة قاسية",
      "hard_acceleration": "تسارع قاسي",
      "hard_cornering": "تقليد قاسي",
      "tampering": "التلاعب",
      "power_on": "تشغيل",
      "power_off": "إيقاف",
      "accident": "حادث",
      "power_restored": "تم إعادة الطاقة",
      "shock": "صدمة",
      "parking_enable": "تمكين الوقوف",
      "door": "باب",
      "advance_notification": "إخطار متقدم",
      "other_navigation": "تصفح آخر",
      "checkout_application_settings_and_other_utility": "تحقق من إعدادات التطبيق والميزات الأخرى",
      "add_your_favorite_place_on_map": "أضف المكان المفضل لديك على الخريطة",
      "mark_virtual_boundaries_on_maps_as_geofence": "علم الحدود الافتراضية على الخرائط \n كـ منطقة جغرافية",
      "settings": "إعدادات",
      "control_your_app_behavior_notifications_and_language": "تحكم في سلوك التطبيق والإخطارات \n واللغة",
      "feedback": "ملاحظات",
      "share_your_valuable_feedback_to_continuous_improvement": "شارك ملاحظاتك القيمة لتطوير مستمر",
      "privacy_policy": "سياسة الخصوصية",
      "data_and_privacy_policy_about_application_uses": "سياسة البيانات والخصوصية حول استخدام التطبيق",
      "tutorials": "دروس",
      "to_know_more_about_fleet_management_and_application_uses": "لمعرفة المزيد عن إدارة الأسطول واستخدام التطبيق",
      "enable_disable_parking": "تمكين/تعطيل الوقوف",
      "list_of_poi": "قائمة POI",
      "profile": "الملف الشخصي",
      "support": "دعم",
      "logout": "تسجيل الخروج",
      "slower_1x": "أبطأ (1x)",
      "slow_2x": "بطيء (2x)",
      "normal_3x": "عادي (3x)",
      "fast_4x": "سريع (4x)",
      "faster_5x": "أسرع (5x)",
      "stoppage": "موقف",
      "date": "تاريخ",
      "time": "وقت",
      "reports": "تقارير",
      "stopage_report": "تقرير الموقف",
      "day_wise_summary": "ملخص يومي",
      "trip_report": "تقرير الرحلة",
      "sensor_report": "تقرير المستشعر",
      "alert_report": "تقرير التنبيه",
      "over_speed_report": "تقرير السرعة الزائدة",
      "set_notifications": "ضبط الإخطارات",
      "language": "لغة",
      "change_the_application_language_as_per_your_compatibility": "غير لغة التطبيق وفقًا للتوافق الخاص بك.",
      "set_the_notification_preference_according_to_the_use_cases": "ضبط تفضيلات الإخطار وفقًا لحالات الاستخدام",
      "protect_user_account": "احمي حساب المستخدم الخاص بك عن طريق تغيير كلمة المرور",
      "support_and_feedback": "دعم وملاحظات",
      "topic_title": "عنوان الموضوع",
      "enter_feedback": "أدخل ملاحظاتك هنا",
      "send_to_admin": "إرسال إلى المسؤول",
      "tracking_link": "رابط التتبع",
      "utility_to_optimize_fleet": "الأداة المستخدمة لتحسين الأسطول",
      "replay": "إعادة التشغيل",
      "checkout_playback_history": "تحقق من تاريخ التشغيل السابق للمركبة الخاصة بك",
      "vehicle_driven_history": "تاريخ قيادة المركبة رسم خط على الخريطة",
      "parking": "وقوف السيارات",
      "manage_vehicle_parking": "يساعدك على إدارة وضع وقوف السيارة الخاصة بك",
      "remote_stop": "توقف عن بعد",
      "force_stop_resume_vehicle": "قم بإيقاف قوة تشغيل المركبة الخاصة بك أو إعادة تشغيلها",
      "get_fleet_related_reports": "احصل على التقارير المتعلقة بالأسطول الخاص بك لتحليل البيانات",
      "track_link": "رابط التتبع",
      "create_share_external_tracking": "إنشاء ومشاركة رابط التتبع الخارجي\n مع شركائك",
      "live_tracking": "تتبع حي",
      "view_history": "عرض التاريخ",
      "add_location": "أضف الموقع",
      "odometer": "عداد المسافة",
      "driven_today": "تم القيادة اليوم",
      "login": "تسجيل الدخول",
      "kindly_enter_username": "يرجى إدخال اسم المستخدم",
      "kindly_enter_password": "يرجى إدخال كلمة المرور",
      "login_success": "تم تسجيل الدخول بنجاح",
      "invalid_username_password": "اسم المستخدم أو كلمة المرور غير صحيحة",
      "demo_account_login_success": "تم تسجيل الدخول إلى الحساب التجريبي بنجاح",
      "choose_language":"اختيار اللغة",
    },

    'ru_RU': {
      "user_login": "Вход пользователя",
      "demo_login": "Демонстрационный вход",
      "username_email": "Имя пользователя или Эл. адрес",
      "password": "Пароль",
      "login_account": "Войдите в свой аккаунт",
      "sign_in_google": " Войти с помощью Google",
      "dont_have_account": "У вас нет аккаунта?",
      "sign_up": "Зарегистрироваться",
      "external_tracking": "Внешнее отслеживание",
      "all_rights_reserved": "Все права защищены. © 2023 ООО «Fleet Stack»",
      "dashboard": "Панель управления",
      "map": "Карта",
      "list": "Список",
      "utility": "Утилита",
      "other": "Другое",
      "about_us": "О нас",
      "about_aiq": "Fleet Stack предлагает самостоятельно размещаемое приложение в соответствии с требованиями клиента и приложением, которое может быть установлено на ваш сервер.\n\nРешение, предлагаемое Fleet Stack, может быть легко установлено на сервере клиента с его собственным логотипом и брендингом, а также доступно на местном языке, что предоставляет им полную свободу использования решения.\n\nFleet Stack также предоставляет команду экспертов для установки и других технических аспектов.",
      "add_point": "Добавить точку",
      "change_password": "Изменить пароль",
      "current_password": "Текущий пароль",
      "new_password": "Новый пароль",
      "confirm_password": "Подтвердите пароль",
      "update_password": "Обновить пароль",
      "running_all": "Все в работе",
      "km": "КМ",
      "ai_smartscale": "AI SmartScale",
      "last_week": "Прошлая неделя",
      "growth": "Рост",
      "fleet_utilization": "Использование транспортного флота",
      "all_vehicles": "Все транспортные средства",
      "units": "Единицы",
      "stop_vehicles": "Остановить транспортные средства",
      "running": "В работе",
      "eco_driving": "Экономичное вождение",
      "good": "Хорошо",
      "driver_behavior": "Поведение водителя",
      "excellent": "Отлично",
      "vehicle_health": "Состояние транспортного средства",
      "warning": "Предупреждение",
      "you_are_doing": "Вы отлично справляетесь!",
      "keep_it_up":"Продолжайте в том же духе и следуйте своему плану!",
      "list_of_geofence": "Список геозон",
      "km_hr": "КМ/ЧАС",
      "map_types": "Типы карты",
      "default": "По умолчанию",
      "satellite": "Спутник",
      "terrain": "Рельеф",
      "map_settings": "Настройки карты",
      "stopage": "Остановка",
      "poi": "ТОЧКА",
      "geofence": "Геозона",
      "stop_resume_vehicle": "Остановка/возобновление транспортного средства",
      "search": "Поиск",
      "all": "Все",
      "stop": "Остановить",
      "idle": "Бездействующий",
      "info": "Информация",
      "history": "История",
      "sensors": "Датчики",
      "details": "Подробности",
      "vehicle_status": "Статус транспортного средства",
      "vehicle_current_status": "Текущий статус транспортного средства",
      "ignition": "Зажигание",
      "ignition_status": "Статус зажигания",
      "today_distance": "Дистанция сегодня",
      "till_now_driven_km": "Пройдено км до сих пор",
      "connected_satellite": "Количество подключенных спутников",
      "speed": "Скорость",
      "vehicle_moving_km_per_hour": "Транспортное средство движется со скоростью в км/час",
      "lat_lon": "Широта/Долгота",
      "latitude_and_longitude": "Широта и долгота",
      "add_new_sensor": "Добавить новый датчик",
      "vehicle": "Транспортное средство",
      "type_of_vehicle": "Тип транспортного средства",
      "imei": "IMEI",
      "gps_device_imei": "IMEI устройства GPS",
      "gps_device": "Устройство GPS",
      "device_type": "Тип устройства",
      "driver": "Водитель",
      "the_person_driving": "Лицо, управляющее транспортным средством",
      "trackline": "Траектория",
      "smooth_tracking": "Плавное отслеживание",
      "ripple": "Колебание",
      "immobilize_vehicle": "Обездвиживание транспортного средства",
      "parking_mode": "Режим стоянки",
      "navigate_to_the_vehicle_location": "Перейти к местоположению транспортного средства",
      "continue": "Продолжить >>",
      "label": "Метка",
      "cluster": "Кластер",
      "select_time": "Выберите время",
      "5_min": "5 мин.",
      "30_min": "30 мин.",
      "1_hour": "1 час",
      "6_hours": "6 часов",
      "1_day": "1 день",
      "notifications": "Уведомления",
      "basic_notification": "Основное уведомление",
      "ignition_on": "Зажигание включено",
      "ignition_off": "Зажигание выключено",
      "sos": "SOS",
      "power_cut": "Отключение электропитания",
      "vibration": "Вибрация",
      "low_battery": "Низкий заряд батареи",
      "hard_braking": "Резкое торможение",
      "hard_acceleration": "Резкое ускорение",
      "hard_cornering": "резкое поворот",
      "tampering": "Нарушение целостности",
      "power_on": "Включение электропитания",
      "power_off": "Отключение электропитания",
      "accident": "Авария",
      "power_restored": "Электропитание восстановлено",
      "shock": "Шок",
      "parking_enable": "Разрешение на стоянку",
      "door": "Дверь",
      "advance_notification": "Расширенное уведомление",
      "other_navigation": "Другая навигация",
      "checkout_application_settings_and_other_utility": "Проверьте настройки приложения и другие утилиты",
      "add_your_favorite_place_on_map": "добавьте свое любимое место на карту",
      "mark_virtual_boundaries_on_maps_as_geofence": "пометьте виртуальные границы на картах \n как геозону",
      "settings": "Настройки",
      "control_your_app_behavior_notifications_and_language": "контролируйте поведение вашего приложения, уведомления \n и язык",
      "feedback": "Обратная связь",
      "share_your_valuable_feedback_to_continuous_improvement": "поделитесь своим ценным отзывом для постоянного улучшения",
      "privacy_policy": "Политика конфиденциальности",
      "data_and_privacy_policy_about_application_uses": "Политика данных и конфиденциальности об использовании приложения",
      "tutorials": "Учебные пособия",
      "to_know_more_about_fleet_management_and_application_uses": "чтобы узнать больше о управлении флотом и использовании приложения",
      "enable_disable_parking": "Включить/Отключить стоянку",
      "list_of_poi": "Список POI",
      "profile": "Профиль",
      "support": "Поддержка",
      "logout": "Выйти",
      "slower_1x": "Медленнее (1x)",
      "slow_2x": "Медленно (2x)",
      "normal_3x": "Нормально (3x)",
      "fast_4x": "Быстро (4x)",
      "faster_5x": "Быстрее (5x)",
      "stoppage": "Остановка",
      "date": "Дата",
      "time": "Время",
      "reports": "Отчеты",
      "stopage_report": "Отчет об остановке",
      "day_wise_summary": "Дневная сводка",
      "trip_report": "Отчет о рейсе",
      "sensor_report": "Отчет о датчиках",
      "alert_report": "Отчет об оповещении",
      "over_speed_report": "Отчет о превышении скорости",
      "set_notifications": "Установка уведомлений",
      "language": "Язык",
      "change_the_application_language_as_per_your_compatibility": "Измените язык приложения согласно\n вашей совместимости.",
      "set_the_notification_preference_according_to_the_use_cases": "Установите предпочтение уведомлений\n согласно сценариям использования",
      "protect_user_account": "Защитите свою учетную запись пользователя\n, изменив пароль",
      "support_and_feedback": "Поддержка и обратная связь",
      "topic_title": "Название темы",
      "enter_feedback": "Введите свою обратную связь здесь",
      "send_to_admin": "Отправить администратору",
      "tracking_link": "Ссылка на отслеживание",
      "utility_to_optimize_fleet": "Утилита, используемая для оптимизации флота",
      "replay": "Повтор",
      "checkout_playback_history": "Просмотрите историю воспроизведения вашего транспортного средства",
      "vehicle_driven_history": "История движения транспортного средства, нарисуйте линию на карте",
      "parking": "Парковка",
      "manage_vehicle_parking": "Поможет управлять режимом парковки вашего транспортного средства",
      "remote_stop": "Удаленная остановка",
      "force_stop_resume_vehicle": "Принудительно остановите или возобновите зажигание вашего транспортного средства",
      "get_fleet_related_reports": "Получите отчеты, связанные с флотом, чтобы анализировать данные",
      "track_link": "Ссылка на отслеживание",
      "create_share_external_tracking": "Создайте и опубликуйте ссылку на внешнее\n отслеживание для своих партнеров",
      "live_tracking": "Онлайн отслеживание",
      "view_history": "Просмотр истории",
      "add_location": "Добавить местоположение",
      "odometer": "Одометр",
      "driven_today": "Пройдено сегодня",
      "login": "Логин",
      "kindly_enter_username": "Пожалуйста, введите имя пользователя",
      "kindly_enter_password": "Пожалуйста, введите пароль",
      "login_success": "Вход выполнен успешно",
      "invalid_username_password": "Неверное имя пользователя или пароль",
      "demo_account_login_success": "Вход в демо-учетную запись успешно выполнен",
      "choose_language":"Выберите язык",
    },


  };
}